[project]
name = "nomos"
version = "0.0.1"
description = "Re-Imagining How we build Reliable AI Agents"
readme = "README.md"
authors = [
    { name = "chandralegend", email = "irugalbandarachandra@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
nomos = "nomos:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
