name: Publish TS SDK

on:
  push:
    tags:
      - 'ts-sdk-v*'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sdk/ts
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm test
      - run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
